name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: runner-set
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
      - uses: chartboost/ruff-action@v1
        with:
          args: format --check
